# Generated by Django 3.2 on 2021-04-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wager_racer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='place',
            field=models.CharField(choices=[('t', 'Favorite Dog'), ('u', 'Outsider')], default='t', max_length=1),
        ),
    ]
