# Generated by Django 3.2 on 2021-05-13 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bet_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='place',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='stake',
        ),
        migrations.RemoveField(
            model_name='racer',
            name='target',
        ),
        migrations.AddField(
            model_name='bet',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bet',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.race'),
        ),
        migrations.AddField(
            model_name='bet',
            name='racer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topdog_racer', to='core.racer'),
        ),
        migrations.AddField(
            model_name='bet',
            name='racer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='underdog_racer', to='core.racer'),
        ),
        migrations.DeleteModel(
            name='Wager',
        ),
    ]
